export class recommendations {
	constructor(_ref: any);
	cancelOperation(_ref2: any): any;
	createAModel(_ref4: any): any;
	createBusinessRule(_ref3: any): any;
	createOrTriggerABuild(_ref5: any): any;
	deleteABuild(_ref8: any): any;
	deleteAModel(_ref11: any): any;
	deleteAllBusinessRules(_ref6: any): any;
	deleteAllUsageFiles(_ref7: any): any;
	deleteBusinessRule(_ref9: any): any;
	deleteCatalogItems(_ref10: any): any;
	deleteUsageFile(_ref12: any): any;
	downloadUsageFile(_ref13: any): any;
	getAModelById(_ref23: any): any;
	getAllBatchJobs(_ref14: any): any;
	getAllBuilds(_ref15: any): any;
	getAllBusinessRules(_ref16: any): any;
	getAllCatalogItems(_ref17: any): any;
	getAllModels(): any;
	getBuildById(_ref18: any): any;
	getBuildDataStatistics(_ref19: any): any;
	getBuildMetrics(_ref20: any): any;
	getBusinessRule(_ref21: any): any;
	getItemToItemRecommendations(_ref22: any): any;
	getModelFeatures(_ref24: any): any;
	getOperationStatus(_ref25: any): any;
	getSpecificCatalogItemsBySearchTerm(_ref26: any): any;
	getUsageStatisticsForABuild(_ref27: any): any;
	getUsageStatisticsForAModel(_ref28: any): any;
	getUserToItemRecommendations(_ref29: any): any;
	listUsageFiles(_ref30: any): any;
	startBatchJob(_ref31: any): any;
	updateCatalogItems(_ref32: any): any;
	updateModel(_ref33: any): any;
	uploadACatalogFileToAModel(_ref34: any): any;
	uploadAUsageFileToAModel(_ref36: any): any;
	uploadUsageEvent(_ref35: any): any;
}
