module.exports = {
    academicKnowledge: require('./knowledge/academicKnowledge'),
    bingAutosuggest: require('./search/bingAutosuggest'),
    bingImageSearch: require('./search/bingImageSearch'),
    bingNewsSearch: require('./search/bingNewsSearch'),
    bingSpellCheck: require('./language/bingSpellCheck'),
    bingVideoSearch: require('./search/bingVideoSearch'),
    bingWebSearch: require('./search/bingWebSearch'),
    computerVision: require('./vision/computerVision'),
    emotion: require('./vision/emotion'),
    entityLinking: require('./knowledge/entityLinking'),
    qnaMaker: require('./knowledge/qnaMaker'),
    face: require('./vision/face'),
    recommendations: require('./knowledge/recommendations'),
    speakerRecognition: require('./speech/speakerRecognition'),
    textAnalytics: require('./language/textAnalytics'),
    video: require('./vision/video'),
    webLanguageModel: require('./language/webLanguageModel'),
    textTranslator: require('./language/textTranslator'),
    bingSpeech: require('./speech/bingSpeech')
};