module.exports = {
    bingAutosuggest: require('./search/bingAutosuggest'),
    bingImageSearch: require('./search/bingImageSearch'),
    bingNewsSearch: require('./search/bingNewsSearch'),
    bingVideoSearch: require('./search/bingVideoSearch'),
    bingWebSearch: require('./search/bingWebSearch'),
    bingAutosuggestV7: require('./search/bingAutosuggestV7'),
    bingImageSearchV7: require('./search/bingImageSearchV7'),
    bingNewsSearchV7: require('./search/bingNewsSearchV7'),
    bingSpellCheckV7: require('./language/bingSpellCheckV7'),
    bingVideoSearchV7: require('./search/bingVideoSearchV7'),
    bingWebSearchV7: require('./search/bingWebSearchV7'),
    computerVision: require('./vision/computerVision'),
    qnaMaker: require('./knowledge/qnaMaker'),
    qnaMakerV4: require('./knowledge/qnaMakerV4'),
    face: require('./vision/face'),
    recommendations: require('./knowledge/recommendations'),
    speakerIdentification: require('./speech/speakerIdentification'),
    speakerVerification: require('./speech/speakerVerification'),
    textAnalytics: require('./language/textAnalytics'),
    languageUnderstanding: require('./language/languageUnderstanding'),
    textTranslator: require('./language/textTranslator'),
    bingSpeech: require('./speech/bingSpeech'),
    bingEntitySearch: require('./search/bingEntitySearch'),
    contentModerator: require('./vision/contentModerator'),
    videoIndexerV2: require('./vision/videoIndexerV2')
};