module.exports = {
    academicKnowledge: require('./academicKnowledge'),
    bingAutosuggest: require('./bingAutosuggest'),
    bingImageSearch: require('./bingImageSearch'),
    bingNewsSearch: require('./bingNewsSearch'),
    bingSpellCheck: require('./bingSpellCheck'),
    bingVideoSearch: require('./bingVideoSearch'),
    bingWebSearch: require('./bingWebSearch'),
    computerVision: require('./computerVision'),
    emotion: require('./emotion'),
    entityLinking: require('./entityLinking'),
    face: require('./face'),
    recommendations: require('./recommendations'),
    speakerRecognition: require('./speakerRecognition'),
    textAnalytics: require('./textAnalytics'),
    video: require('./video'),
    webLanguageModel: require('./webLanguageModel'),
};